const pickExport = (mod, exportName, componentName, path) => {
  const resolved = exportName === 'default' ? mod?.default : mod?.[exportName]
  if (!resolved) {
    throw new Error(`[nuxt-content] Missing export "${exportName}" for component "${componentName}" in "${path}".`)
  }
  return resolved
}
export const localComponentLoaders = {
  AdminBlockCard: () => import("./../../app/components/admin/AdminBlockCard.vue").then(m => pickExport(m, "default", "AdminBlockCard", "./../../app/components/admin/AdminBlockCard.vue")),
  AdminFormCard: () => import("./../../app/components/admin/AdminFormCard.vue").then(m => pickExport(m, "default", "AdminFormCard", "./../../app/components/admin/AdminFormCard.vue")),
  AdminHero: () => import("./../../app/components/admin/AdminHero.vue").then(m => pickExport(m, "default", "AdminHero", "./../../app/components/admin/AdminHero.vue")),
  AdminInspector: () => import("./../../app/components/admin/AdminInspector.vue").then(m => pickExport(m, "default", "AdminInspector", "./../../app/components/admin/AdminInspector.vue")),
  AdminPanel: () => import("./../../app/components/admin/AdminPanel.vue").then(m => pickExport(m, "default", "AdminPanel", "./../../app/components/admin/AdminPanel.vue")),
  AdminPreviewPanel: () => import("./../../app/components/admin/AdminPreviewPanel.vue").then(m => pickExport(m, "default", "AdminPreviewPanel", "./../../app/components/admin/AdminPreviewPanel.vue")),
  AdminSidebar: () => import("./../../app/components/admin/AdminSidebar.vue").then(m => pickExport(m, "default", "AdminSidebar", "./../../app/components/admin/AdminSidebar.vue")),
  AdminStatCard: () => import("./../../app/components/admin/AdminStatCard.vue").then(m => pickExport(m, "default", "AdminStatCard", "./../../app/components/admin/AdminStatCard.vue")),
  AdminTabs: () => import("./../../app/components/admin/AdminTabs.vue").then(m => pickExport(m, "default", "AdminTabs", "./../../app/components/admin/AdminTabs.vue")),
  AdminTopbar: () => import("./../../app/components/admin/AdminTopbar.vue").then(m => pickExport(m, "default", "AdminTopbar", "./../../app/components/admin/AdminTopbar.vue")),
  BlogComposerPreview: () => import("./../../app/components/admin/BlogComposerPreview.vue").then(m => pickExport(m, "default", "BlogComposerPreview", "./../../app/components/admin/BlogComposerPreview.vue")),
  BrandMark: () => import("./../../app/components/base/BrandMark.vue").then(m => pickExport(m, "default", "BrandMark", "./../../app/components/base/BrandMark.vue")),
  StatusBadge: () => import("./../../app/components/base/StatusBadge.vue").then(m => pickExport(m, "default", "StatusBadge", "./../../app/components/base/StatusBadge.vue")),
  TagPill: () => import("./../../app/components/base/TagPill.vue").then(m => pickExport(m, "default", "TagPill", "./../../app/components/base/TagPill.vue")),
  ThemeToggle: () => import("./../../app/components/base/ThemeToggle.vue").then(m => pickExport(m, "default", "ThemeToggle", "./../../app/components/base/ThemeToggle.vue")),
  ActiveProjectsBlock: () => import("./../../app/components/blocks/ActiveProjectsBlock.vue").then(m => pickExport(m, "default", "ActiveProjectsBlock", "./../../app/components/blocks/ActiveProjectsBlock.vue")),
  ArticleHero: () => import("./../../app/components/blocks/ArticleHero.vue").then(m => pickExport(m, "default", "ArticleHero", "./../../app/components/blocks/ArticleHero.vue")),
  BuildLogBlock: () => import("./../../app/components/blocks/BuildLogBlock.vue").then(m => pickExport(m, "default", "BuildLogBlock", "./../../app/components/blocks/BuildLogBlock.vue")),
  ContentBlockRenderer: () => import("./../../app/components/blocks/ContentBlockRenderer.vue").then(m => pickExport(m, "default", "ContentBlockRenderer", "./../../app/components/blocks/ContentBlockRenderer.vue")),
  DocsHero: () => import("./../../app/components/blocks/DocsHero.vue").then(m => pickExport(m, "default", "DocsHero", "./../../app/components/blocks/DocsHero.vue")),
  FeaturedProjectBlock: () => import("./../../app/components/blocks/FeaturedProjectBlock.vue").then(m => pickExport(m, "default", "FeaturedProjectBlock", "./../../app/components/blocks/FeaturedProjectBlock.vue")),
  HeroIntroBlock: () => import("./../../app/components/blocks/HeroIntroBlock.vue").then(m => pickExport(m, "default", "HeroIntroBlock", "./../../app/components/blocks/HeroIntroBlock.vue")),
  LabHero: () => import("./../../app/components/blocks/LabHero.vue").then(m => pickExport(m, "default", "LabHero", "./../../app/components/blocks/LabHero.vue")),
  LabsTracksBlock: () => import("./../../app/components/blocks/LabsTracksBlock.vue").then(m => pickExport(m, "default", "LabsTracksBlock", "./../../app/components/blocks/LabsTracksBlock.vue")),
  ManifestoBlock: () => import("./../../app/components/blocks/ManifestoBlock.vue").then(m => pickExport(m, "default", "ManifestoBlock", "./../../app/components/blocks/ManifestoBlock.vue")),
  NewsletterBlock: () => import("./../../app/components/blocks/NewsletterBlock.vue").then(m => pickExport(m, "default", "NewsletterBlock", "./../../app/components/blocks/NewsletterBlock.vue")),
  ProjectHero: () => import("./../../app/components/blocks/ProjectHero.vue").then(m => pickExport(m, "default", "ProjectHero", "./../../app/components/blocks/ProjectHero.vue")),
  ProjectMetaGrid: () => import("./../../app/components/blocks/ProjectMetaGrid.vue").then(m => pickExport(m, "default", "ProjectMetaGrid", "./../../app/components/blocks/ProjectMetaGrid.vue")),
  RelatedContent: () => import("./../../app/components/blocks/RelatedContent.vue").then(m => pickExport(m, "default", "RelatedContent", "./../../app/components/blocks/RelatedContent.vue")),
  SectionHero: () => import("./../../app/components/blocks/SectionHero.vue").then(m => pickExport(m, "default", "SectionHero", "./../../app/components/blocks/SectionHero.vue")),
  ThinkingArticlesBlock: () => import("./../../app/components/blocks/ThinkingArticlesBlock.vue").then(m => pickExport(m, "default", "ThinkingArticlesBlock", "./../../app/components/blocks/ThinkingArticlesBlock.vue")),
  ArticleCard: () => import("./../../app/components/cards/ArticleCard.vue").then(m => pickExport(m, "default", "ArticleCard", "./../../app/components/cards/ArticleCard.vue")),
  ContentCard: () => import("./../../app/components/cards/ContentCard.vue").then(m => pickExport(m, "default", "ContentCard", "./../../app/components/cards/ContentCard.vue")),
  HeroCard: () => import("./../../app/components/cards/HeroCard.vue").then(m => pickExport(m, "default", "HeroCard", "./../../app/components/cards/HeroCard.vue")),
  LabCard: () => import("./../../app/components/cards/LabCard.vue").then(m => pickExport(m, "default", "LabCard", "./../../app/components/cards/LabCard.vue")),
  ProjectCard: () => import("./../../app/components/cards/ProjectCard.vue").then(m => pickExport(m, "default", "ProjectCard", "./../../app/components/cards/ProjectCard.vue")),
  RepositoryCard: () => import("./../../app/components/cards/RepositoryCard.vue").then(m => pickExport(m, "default", "RepositoryCard", "./../../app/components/cards/RepositoryCard.vue")),
  DocsSidebar: () => import("./../../app/components/docs/DocsSidebar.vue").then(m => pickExport(m, "default", "DocsSidebar", "./../../app/components/docs/DocsSidebar.vue")),
  DocsToc: () => import("./../../app/components/docs/DocsToc.vue").then(m => pickExport(m, "default", "DocsToc", "./../../app/components/docs/DocsToc.vue")),
  PublicNav: () => import("./../../app/components/layout/PublicNav.vue").then(m => pickExport(m, "default", "PublicNav", "./../../app/components/layout/PublicNav.vue")),
  SiteFooter: () => import("./../../app/components/layout/SiteFooter.vue").then(m => pickExport(m, "default", "SiteFooter", "./../../app/components/layout/SiteFooter.vue")),
  ProjectOverviewRenderer: () => import("./../../app/components/projects/ProjectOverviewRenderer.vue").then(m => pickExport(m, "default", "ProjectOverviewRenderer", "./../../app/components/projects/ProjectOverviewRenderer.vue")),
  NuxtWelcome: () => import("./../../node_modules/nuxt/dist/app/components/welcome.vue").then(m => pickExport(m, "default", "NuxtWelcome", "./../../node_modules/nuxt/dist/app/components/welcome.vue")),
  NuxtLayout: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-layout").then(m => pickExport(m, "default", "NuxtLayout", "./../../node_modules/nuxt/dist/app/components/nuxt-layout")),
  NuxtErrorBoundary: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").then(m => pickExport(m, "default", "NuxtErrorBoundary", "./../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")),
  ClientOnly: () => import("./../../node_modules/nuxt/dist/app/components/client-only").then(m => pickExport(m, "default", "ClientOnly", "./../../node_modules/nuxt/dist/app/components/client-only")),
  DevOnly: () => import("./../../node_modules/nuxt/dist/app/components/dev-only").then(m => pickExport(m, "default", "DevOnly", "./../../node_modules/nuxt/dist/app/components/dev-only")),
  ServerPlaceholder: () => import("./../../node_modules/nuxt/dist/app/components/server-placeholder").then(m => pickExport(m, "default", "ServerPlaceholder", "./../../node_modules/nuxt/dist/app/components/server-placeholder")),
  NuxtLink: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-link").then(m => pickExport(m, "default", "NuxtLink", "./../../node_modules/nuxt/dist/app/components/nuxt-link")),
  NuxtLoadingIndicator: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").then(m => pickExport(m, "default", "NuxtLoadingIndicator", "./../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")),
  NuxtTime: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-time.vue").then(m => pickExport(m, "default", "NuxtTime", "./../../node_modules/nuxt/dist/app/components/nuxt-time.vue")),
  NuxtRouteAnnouncer: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").then(m => pickExport(m, "default", "NuxtRouteAnnouncer", "./../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")),
  NuxtAnnouncer: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-announcer").then(m => pickExport(m, "default", "NuxtAnnouncer", "./../../node_modules/nuxt/dist/app/components/nuxt-announcer")),
  NuxtImg: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-stubs").then(m => pickExport(m, "NuxtImg", "NuxtImg", "./../../node_modules/nuxt/dist/app/components/nuxt-stubs")),
  NuxtPicture: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-stubs").then(m => pickExport(m, "NuxtPicture", "NuxtPicture", "./../../node_modules/nuxt/dist/app/components/nuxt-stubs")),
  ContentRenderer: () => import("./../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").then(m => pickExport(m, "default", "ContentRenderer", "./../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")),
  NuxtPage: () => import("./../../node_modules/nuxt/dist/pages/runtime/page").then(m => pickExport(m, "default", "NuxtPage", "./../../node_modules/nuxt/dist/pages/runtime/page")),
  NoScript: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "NoScript", "NoScript", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Link: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Link", "Link", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Base: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Base", "Base", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Title: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Title", "Title", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Meta: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Meta", "Meta", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Style: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Style", "Style", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Head: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Head", "Head", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Html: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Html", "Html", "./../../node_modules/nuxt/dist/head/runtime/components")),
  Body: () => import("./../../node_modules/nuxt/dist/head/runtime/components").then(m => pickExport(m, "Body", "Body", "./../../node_modules/nuxt/dist/head/runtime/components")),
  MDC: () => import("./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").then(m => pickExport(m, "default", "MDC", "./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")),
  MDCCached: () => import("./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue").then(m => pickExport(m, "default", "MDCCached", "./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")),
  MDCRenderer: () => import("./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").then(m => pickExport(m, "default", "MDCRenderer", "./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")),
  MDCSlot: () => import("./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").then(m => pickExport(m, "default", "MDCSlot", "./../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")),
  NuxtIsland: () => import("./../../node_modules/nuxt/dist/app/components/nuxt-island").then(m => pickExport(m, "default", "NuxtIsland", "./../../node_modules/nuxt/dist/app/components/nuxt-island")),
}
export const globalComponents: string[] = ["ProseA","ProseBlockquote","ProseCode","ProseEm","ProseH1","ProseH2","ProseH3","ProseH4","ProseH5","ProseH6","ProseHr","ProseImg","ProseLi","ProseOl","ProseP","ProsePre","ProseScript","ProseStrong","ProseTable","ProseTbody","ProseTd","ProseTh","ProseThead","ProseTr","ProseUl"]
export const localComponents: string[] = ["AdminBlockCard","AdminFormCard","AdminHero","AdminInspector","AdminPanel","AdminPreviewPanel","AdminSidebar","AdminStatCard","AdminTabs","AdminTopbar","BlogComposerPreview","BrandMark","StatusBadge","TagPill","ThemeToggle","ActiveProjectsBlock","ArticleHero","BuildLogBlock","ContentBlockRenderer","DocsHero","FeaturedProjectBlock","HeroIntroBlock","LabHero","LabsTracksBlock","ManifestoBlock","NewsletterBlock","ProjectHero","ProjectMetaGrid","RelatedContent","SectionHero","ThinkingArticlesBlock","ArticleCard","ContentCard","HeroCard","LabCard","ProjectCard","RepositoryCard","DocsSidebar","DocsToc","PublicNav","SiteFooter","ProjectOverviewRenderer","NuxtWelcome","NuxtLayout","NuxtErrorBoundary","ClientOnly","DevOnly","ServerPlaceholder","NuxtLink","NuxtLoadingIndicator","NuxtTime","NuxtRouteAnnouncer","NuxtAnnouncer","NuxtImg","NuxtPicture","ContentRenderer","NuxtPage","NoScript","Link","Base","Title","Meta","Style","Head","Html","Body","MDC","MDCCached","MDCRenderer","MDCSlot","NuxtIsland"]