export const checksums = {
  "blog": "v3.5.0--OtZY6lak3tcinV1-Ph_-UkIcOt2XKJnpvAW5deby6Qc",
  "projects": "v3.5.0--eAxVmLMTUPEHWbppvY6enu_B-lPJEcfeihP5dkxRA4w",
  "docs": "v3.5.0--o5DA0mIqL_TXxQYwX5LOoXnDuiEBxPh67_CLCVZrG8Y",
  "labs": "v3.5.0--VWvAkOp_4kqF5bcNfOE9H0Wka9wlKvxhLz4sORA_iyE",
  "home": "v3.5.0--6rGrv_50488GBaS_204B3ISzDX9dQgleInb1ky9gRJo",
  "settings": "v3.5.0--7NdHW3U4wwSq3Ia4uCr0UVNrNwsOoJSUDSevpNoDzt0"
}
export const checksumsStructure = {
  "blog": "HgiavfbRY-6HTrcyV6bFUbVpHh0Fu8-bBSQgJaL1Eok",
  "projects": "ghGh8LWlReOvx3tQoFGDsw7wwKMuPKW7BWKoGMmY2jo",
  "docs": "ikhwkEO43qpXZKvFHiSSKrkBOvOqnzybQBnJjInMINk",
  "labs": "IA7318SIMAnuJVIwwKXY6-D649IlKXot3TzcLsBVdR8",
  "home": "mk-tLIReAPgs28M1s8MdR795Twcc4eXp3Dv3oYnGS4E",
  "settings": "HRPrPWOq90oDSymRhxY64nXZuq9JhSLBKqaYKakfBIo"
}

export const tables = {
  "blog": "_content_blog",
  "projects": "_content_projects",
  "docs": "_content_docs",
  "labs": "_content_labs",
  "home": "_content_home",
  "settings": "_content_settings",
  "info": "_content_info"
}

export default {
  "blog": {
    "type": "page",
    "fields": {
      "id": "string",
      "title": "string",
      "accentColor": "string",
      "archivedAt": "string",
      "author": "string",
      "blocks": "json",
      "body": "json",
      "canonical": "string",
      "category": "string",
      "coverAlt": "string",
      "coverCaption": "string",
      "coverImage": "string",
      "coverPosition": "string",
      "coverStyle": "string",
      "date": "string",
      "description": "string",
      "excerpt": "string",
      "extension": "string",
      "lab": "string",
      "mediaRefs": "json",
      "meta": "json",
      "navigation": "json",
      "noindex": "boolean",
      "ogDescription": "string",
      "ogImage": "string",
      "ogTitle": "string",
      "path": "string",
      "readingTime": "string",
      "seo": "json",
      "seoDescription": "string",
      "seoTitle": "string",
      "slug": "string",
      "status": "string",
      "stem": "string",
      "tags": "json",
      "type": "string",
      "updatedAt": "string"
    }
  },
  "projects": {
    "type": "page",
    "fields": {
      "id": "string",
      "title": "string",
      "accentColor": "string",
      "blocks": "json",
      "body": "json",
      "buildLogIntro": "string",
      "buildLogNote": "string",
      "canonical": "string",
      "coverAlt": "string",
      "coverCaption": "string",
      "coverImage": "string",
      "coverPosition": "string",
      "coverStyle": "string",
      "date": "string",
      "decisionTraceBody": "string",
      "decisionTraceTitle": "string",
      "description": "string",
      "docsFolder": "string",
      "docsPath": "string",
      "docsPaths": "json",
      "documentationIntro": "string",
      "emptyDocumentationBody": "string",
      "emptyDocumentationTitle": "string",
      "extension": "string",
      "lab": "string",
      "mediaRefs": "json",
      "meta": "json",
      "navigation": "json",
      "noindex": "boolean",
      "ogDescription": "string",
      "ogImage": "string",
      "ogTitle": "string",
      "overviewAccentColor": "string",
      "overviewBackgroundMode": "string",
      "overviewHeroStyle": "string",
      "overviewPayload": "json",
      "overviewSecondaryAccent": "string",
      "path": "string",
      "projectHoldsBody": "string",
      "projectHoldsTitle": "string",
      "projectIndex": "string",
      "projectIndexIntro": "string",
      "projectMemory": "string",
      "projectMemoryBody": "string",
      "projectMemoryIntro": "string",
      "projectMemoryTitle": "string",
      "projectOverviewBody": "string",
      "projectOverviewTitle": "string",
      "relatedArticles": "json",
      "relatedArticlesNote": "string",
      "relatedBlogSlugs": "json",
      "relatedDocs": "json",
      "relatedPosts": "json",
      "seo": "json",
      "seoDescription": "string",
      "seoTitle": "string",
      "slug": "string",
      "stack": "json",
      "status": "string",
      "stem": "string",
      "summary": "string",
      "tags": "json",
      "type": "string",
      "updatedAt": "string",
      "workingStackNote": "string",
      "year": "number"
    }
  },
  "docs": {
    "type": "page",
    "fields": {
      "id": "string",
      "title": "string",
      "accentColor": "string",
      "blocks": "json",
      "body": "json",
      "canonical": "string",
      "coverAlt": "string",
      "coverCaption": "string",
      "coverImage": "string",
      "coverPosition": "string",
      "coverStyle": "string",
      "date": "string",
      "description": "string",
      "docsFolder": "string",
      "extension": "string",
      "lab": "string",
      "mediaRefs": "json",
      "meta": "json",
      "navigation": "json",
      "noindex": "boolean",
      "ogDescription": "string",
      "ogImage": "string",
      "ogTitle": "string",
      "order": "number",
      "path": "string",
      "project": "string",
      "projectSlug": "string",
      "section": "string",
      "seo": "json",
      "seoDescription": "string",
      "seoTitle": "string",
      "slug": "string",
      "status": "string",
      "stem": "string",
      "tags": "json",
      "updatedAt": "string"
    }
  },
  "labs": {
    "type": "page",
    "fields": {
      "id": "string",
      "title": "string",
      "accent": "string",
      "body": "json",
      "canonical": "string",
      "description": "string",
      "extension": "string",
      "featured": "boolean",
      "meta": "json",
      "navigation": "json",
      "noindex": "boolean",
      "ogDescription": "string",
      "ogImage": "string",
      "ogTitle": "string",
      "openQuestions": "json",
      "order": "number",
      "path": "string",
      "relatedTags": "json",
      "roadmap": "json",
      "seo": "json",
      "seoDescription": "string",
      "seoTitle": "string",
      "shortTitle": "string",
      "slug": "string",
      "status": "string",
      "stem": "string"
    }
  },
  "home": {
    "type": "data",
    "fields": {
      "id": "string",
      "extension": "string",
      "meta": "json",
      "stem": "string"
    }
  },
  "settings": {
    "type": "data",
    "fields": {
      "id": "string",
      "extension": "string",
      "meta": "json",
      "stem": "string"
    }
  },
  "info": {
    "type": "data",
    "fields": {}
  }
}